using System.Text;
using mazharenko.AoCAgent.Generator.Mics;
using mazharenko.AoCAgent.Generator.Sources;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Trivia = mazharenko.AoCAgent.Generator.Mics.Trivia;

namespace mazharenko.AoCAgent.Generator;

internal partial class DaysGenerator
{
	private void GenerateBaseTypes(SourceProductionContext productionContext, DaySource day)
	{
		productionContext.CancellationToken.ThrowIfCancellationRequested();
		
		var ns = day.Syntax.GetContainingNamespace();

		var dayWithBase =
			ClassDeclaration(day.Syntax.Identifier)
				.AddAttributeLists(CodeGeneratedAttribute.AsSyntax)
				.AddModifiers(
					Token(SyntaxKind.PartialKeyword)
				).AddMembers(
					GeneratePartBaseDeclaration("Part1", day.Part1),
					GeneratePartBaseDeclaration("Part2", day.Part2)
				);
		var newRoot =
			CompilationUnit()
				.AddDefaultUsings()
				.WithMembers(
					ns is null
						? SingletonList<MemberDeclarationSyntax>(dayWithBase)
						: SingletonList<MemberDeclarationSyntax>(
							NamespaceDeclaration(ns)
								.AddMembers(
									dayWithBase
								)
						)
				).WithLeadingTrivia(
					AutoGeneratedComment,
					RestoreNullable
				);
		
		productionContext.AddSource($"{day.Year}.{day.Syntax.Identifier.ValueText}.Base.g.cs", SourceText.From(
			newRoot.NormalizeWhitespace(indentation: "\t").ToFullString(),
			Encoding.UTF8
		));
	}

	private static IEnumerable<MemberDeclarationSyntax> GeneratePartMembers(PartSource part)
	{
		if (part.IsStringInput)
		{
			yield return ParseMemberDeclaration(
				$"""
				public {part.InputType.ToDisplayString()} ParseObtained(string input) => input.Trim();
				""")!;
		}

		if (part.IsStringRes && part.ResType.NullableAnnotation != NullableAnnotation.Annotated)
		{
			yield return ParseMemberDeclaration(
				"""
				public sealed override string Format(string res) => res;
				"""
			)!;
		}

		var examples =
			part.PartClass.Members.OfType<FieldDeclarationSyntax>()
				.Where(field => field.Declaration.Type.ToString() == "Example")
				.SelectMany(exampleField => exampleField.Declaration.Variables)
				.ToList();

		if (examples.Count == 0)
			yield return MethodDeclaration(
					ParseTypeName("System.Collections.Generic.IEnumerable<NamedExample>"),
					Identifier("GetExamples")
				).AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.OverrideKeyword))
				.WithBody(Block(
					YieldStatement(SyntaxKind.YieldBreakStatement)
				));
		else
			yield return MethodDeclaration(
					ParseTypeName("System.Collections.Generic.IEnumerable<NamedExample>"),
					Identifier("GetExamples")
				).AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.OverrideKeyword))
				.WithBody(Block(
					List(
						examples.Select(exampleVariable =>
							YieldStatement(SyntaxKind.YieldReturnStatement,
								ObjectCreationExpression(ParseTypeName("NamedExample"))
									.WithArgumentList(ArgumentList(
										SeparatedList(new ExpressionSyntax[]
										{
											LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(exampleVariable.Identifier.ValueText)),
											part.ResType.IsValueType
												? ObjectCreationExpression(GenericName(Identifier("ExampleAdapter"))
														.AddTypeArgumentListArguments(IdentifierName(part.ResType.ToDisplayString())))
													.AddArgumentListArguments(Argument(IdentifierName(exampleVariable.Identifier)))
												: CastExpression(
													// explicit cast to workaround NRT warnings
													ParseTypeName("IExample<object>"),
													IdentifierName(exampleVariable.Identifier)
												)
										}.Select(Argument))
									))
							)
						)
					)
				));
		
		yield return ParseMemberDeclaration(
			"""
			public sealed override string SolveObtained(string input)
			{
				return Format(Solve(ParseObtained(input)));
			}
			"""
		)!;
		yield return ParseMemberDeclaration(
			$$"""
			private record Example({{part.InputType.ToDisplayString()}} Input, {{part.ResType.ToDisplayString()}} Expectation) : IExample<{{part.ResType.ToDisplayString()}}>
			{
				private string expectationFormatted = null!;
				private static {{part.PartType.ToDisplayString()}} part = new {{part.PartType.ToDisplayString()}}();
				public {{part.ResType.ToDisplayString()}} Run()
				{
					return part.Solve(Input);
				}
				public {{part.ResType.ToDisplayString()}} RunFormat(out string formatted)
				{
					var res = Run();
					formatted = part.Format(res);
					return res;
				}
				public string ExpectationFormatted => expectationFormatted ??= part.Format(Expectation);
			}
			"""
		)!;
	}
	private static ClassDeclarationSyntax GeneratePartBaseDeclaration(string identifier, PartSource part)
	{
		return ClassDeclaration(identifier)
			.AddModifiers(Token(SyntaxKind.PartialKeyword))
			.AddBaseListTypes(
				SimpleBaseType(
					GenericName(Identifier("PartBase"), TypeArgumentList(
						SeparatedList(new[]
						{
							ParseTypeName(part.InputType.ToDisplayString()),
							ParseTypeName(part.ResType.ToDisplayString())
						})
					))
				), SimpleBaseType(
					GenericName(Identifier("IPart"), TypeArgumentList(
						SeparatedList(new[]
						{
							ParseTypeName(part.InputType.ToDisplayString()),
							ParseTypeName(part.ResType.ToDisplayString())
						})
					))
				)
			).WithMembers(
				List(
					GeneratePartMembers(part)
				)
			);
	}
}