using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace mazharenko.AoCAgent.Generator.Mics;

public static class Trivia
{
	public static SyntaxTrivia AutoGeneratedComment = Comment("// <auto-generated />");
	public static SyntaxTrivia RestoreNullable = Trivia(NullableDirectiveTrivia(Token(SyntaxKind.RestoreKeyword), true));
	public static string RestoreNullableString = "#nullable restore";
}