name: Build

on:
  push:
    branches:
      - '**'
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
      
defaults:
  run:
    shell: pwsh

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: dotnet test -c Release
    
  publish_nuget:
    runs-on: ubuntu-20.04
    if: github.ref_type == 'tag'
    needs: [ test ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish NuGet package
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            pwsh -file "./build/publish.ps1" -version ${{ github.ref_name }} -nugetApiKey "${{ secrets.NUGET_APIKEY }}"